
create table flashcards (
  id bigint generated by default as identity primary key,
  front text not null,
  back text not null,
  ease real default 2.5,
  interval integer default 1,
  due_date date default now()
);
